GET http://localhost:5000/auth/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODNiYTRiNDM5OGYyYmNlM2M2NjM3ZCIsInVzZXJuYW1lIjoidXNlcjkiLCJpYXQiOjE2Njk1Nzk0NDIsImV4cCI6MTY2OTY2NTg0Mn0.nV0cPPcFNDPP4KLnNLIkHiGaHQj5Nd3KdQ4qVctphZY