PUT http://localhost:5000/vacancy HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzODNiYTRiNDM5OGYyYmNlM2M2NjM3ZCIsInVzZXJuYW1lIjoidXNlcjkiLCJpYXQiOjE2Njk1Nzk2MTIsImV4cCI6MTY2OTY2NjAxMn0.gPBSm8vxMSZgP3g-DW_k-niUoxeJbCNd_iTOcWBOxT4

{
   "id": "63839700936d0a54428ff859",
    "companyName": "Bosh1111111111111111111111",
  "companyURL": "http://www.Bosh.com",
  "source": "asddfgh",
  "sourceURL": "qwerty",
  "position": "junior",
  "salary": 5000,
  "status": "3",
  "rank": 2
}